name: "basic"

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cvxgrp/.github/actions/test@main
      with:
        #os: 'ubuntu-latest'
        python-version: '3.10'

    - uses: pre-commit/action@v3.0.0
