name: "book"

on:
- push

jobs:
  #marimo:
  #  runs-on: "ubuntu-latest"
  #  steps:
  #    - uses: cvxgrp/.github/actions/uv/marimo@2.0.0

  #sphinx:
  #  runs-on: "ubuntu-latest"
  #  steps:
  #    - uses: cvxgrp/.github/actions/uv/sphinx@2.0.0

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/pdoc@2.0.0

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/coverage@2.0.0

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/jupyter@2.0.0

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      contents: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/book@2.0.0
